<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            [
                'title' => 'Introduction to Cloud Computing',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/f3/5d00cbdb784bee9e7ff6d4bbab1ebb/CloudComputingIntroduction.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/introduction-to-cloud',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 7031,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 1,
                'platform_id' => 1,
            ],
            [
                'title' => 'AWS Certified Cloud Practitioner (CLF-C02)',
                'image' => 'https://img-c.udemycdn.com/course/240x135/4783354_4d9d_11.jpg',
                'link' => 'https://www.udemy.com/course/certified-cloud-practitioner-aws/',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 7323,
                'price' => 13.99,
                'old_price' => 59.99,
                'language_id' => 3,
                'category_id' => 1,
                'topic_id' => 1,
                'platform_id' => 5,
            ],
            [
                'title' => 'Google Cloud Cybersecurity Professional Certificate',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/6a/4adaf7eb5144b1b5ac3e46d520e791/Course-1--1080x1080.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/professional-certificates/google-cloud-cybersecurity-certificate',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 244,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 1,
                'platform_id' => 1,
            ],
            [
                'title' => 'Bulut Bilişim Temelleri ve AWS Çözüm Mimarlığına Giriş',
                'image' => 'https://img-c.udemycdn.com/course/240x135/2201808_1f49_3.jpg',
                'link' => 'https://www.udemy.com/course/bulut-bilisim-temelleri-ve-aws-cozum-mimarligina-giris/?couponCode=ST10MT30325G1',
                'level' => 'intermediate',
                'rating' => 4.8,
                'total_reviews' => 2200,
                'price' => 10.99,
                'old_price' => 54.99,
                'language_id' => 5,
                'category_id' => 1,
                'topic_id' => 1,
                'platform_id' => 5,
            ],
            [
                'title' => 'Cloud Developer',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F670987d8_nd9990%2Fnd9990.jpg&w=1080&q=75',
                'link' => 'https://www.udacity.com/course/cloud-developer-nanodegree--nd9990?promo=LEARNAI&coupon=MARCHSAVE&utm_source=gsem_brand&utm_medium=ads_r&utm_campaign=22170495779_c_individuals&utm_term=174772232355&utm_keyword=cloud%20nanodegree_p&utm_source=gsem_brand&utm_medium=ads_r&utm_campaign=22170495779_c_individuals&utm_term=174772232355&utm_keyword=cloud%20nanodegree_p&gad_source=1&gclid=CjwKCAiArKW-BhAzEiwAZhWsIBIfNLeKaGW6Tep2qIeG6JrqCCCMQqvmSYwE0RqFBdbs6tkhbOrU3BoCxFYQAvD_BwE',
                'level' => 'intermediate',
                'rating' => 4.4,
                'total_reviews' => 460,
                'price' => 497,
                'old_price' => 794,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 1,
                'platform_id' => 4,
            ],

            [
                'title' => 'Ethical Hacker',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F670987b2_nd350%2Fnd350.jpg&w=1080&q=75',
                'link' => 'https://www.udacity.com/course/ethical-hacker-nanodegree--nd350',
                'level' => 'expert',
                'rating' => 4.1,
                'total_reviews' => 23,
                'price' => 3560,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 2,
                'platform_id' => 4,
            ],
            [
                'title' => 'Site Reliability Engineer',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F67098779_nd087%2Fnd087.jpg&w=1080&q=75',
                'link' => 'https://www.udacity.com/course/site-reliability-engineer-nanodegree--nd087',
                'level' => 'intermediate',
                'rating' => 4.5,
                'total_reviews' => 11,
                'price' => 3560,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 2,
                'platform_id' => 4,
            ],
            [
                'title' => 'IT Security: Defense against the digital dark arts',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/af/d5ed10f26911e7a930e510b0715979/Course-Logo-6---NEW.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=320&h=180&fit=crop&q=50&crop=faces 2x',
                'link' => 'https://www.coursera.org/learn/it-security',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 24214,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 2,
                'platform_id' => 1,
            ],
            [
                'title' => 'JavaScript Security Specialization',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/d0/c49f203314409a9ece74ae6e23339c/Coursera_Javascript_Security_600x600.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/specializations/javascript-security',
                'level' => 'intermediate',
                'rating' => 4.5,
                'total_reviews' => 84,
                'price' => 0,
                'old_price' => null,
                'language_id' => 4,
                'category_id' => 1,
                'topic_id' => 2,
                'platform_id' => 1,
            ],
            [
                'title' => 'تعلم القرصنه واختبار الاختراق بشكل صحيح من الصفر (كورس كامل)',
                'image' => 'https://img-c.udemycdn.com/course/240x135/4169652_d711.jpg',
                'link' => 'https://www.udemy.com/course/yousdnzk/?couponCode=ST10MT30325G1',
                'level' => 'beginner',
                'rating' => 4.3,
                'total_reviews' => 247,
                'price' => 12.99,
                'old_price' => 49.99,
                'language_id' => 2,
                'category_id' => 1,
                'topic_id' => 2,
                'platform_id' => 5,
            ],

            [
                'title' => '深度学习模型部署与剪枝优化实例',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3238711_95c2.jpg',
                'link' => 'https://www.udemy.com/course/deep-learning-tyd/',
                'level' => 'expert',
                'rating' => 4.6,
                'total_reviews' => 7,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 9,
                'category_id' => 1,
                'topic_id' => 3,
                'platform_id' => 5,
            ],
            [
                'title' => 'Deploy Infrastructure as Code (IAC)',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F67098539_cd12352%2Fcd12352.jpg&w=1080&q=75',
                'link' => 'https://www.udacity.com/course/deploy-infrastructure-as-code--cd12352',
                'level' => 'intermediate',
                'rating' => null,
                'total_reviews' => null,
                'price' => 477,
                'old_price' => 794,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 3,
                'platform_id' => 4,
            ],
            [
                'title' => 'Advanced Network Security Specialization',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/db/624680831c4c4b8f4fa77e50e5547a/ANSLogo.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/specializations/advanced-network-security',
                'level' => 'expert',
                'rating' => 4.4,
                'total_reviews' => 32,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 3,
                'platform_id' => 1,
            ],
            [
                'title' => 'Network Security',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/8c/34640457df4f3881f192a69bfb226a/CC-D4-Badge_800x800.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/-network-security',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 199,
                'price' => 0,
                'old_price' => null,
                'language_id' => 7,
                'category_id' => 1,
                'topic_id' => 3,
                'platform_id' => 1,
            ],

            [
                'title' => 'Security Engineer',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F670987c2_nd698%2Fnd698.jpg&w=1080&q=75',
                'link' => 'https://www.udacity.com/course/security-engineer-nanodegree--nd698',
                'level' => 'intermediate',
                'rating' => 4.7,
                'total_reviews' => 33,
                'price' => 3560,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 4,
                'platform_id' => 4,
            ],
            [
                'title' => 'Operating Systems and You: Becoming a Power User',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/e1/0e0c80f1ad11e7b6d1f97cbfd7d592/Course-Logo-3.jpg?auto=format%2Ccompress%2C%20enhance&dpr=2&w=320&h=180&fit=crop&q=50&crop=faces',
                'link' => 'https://www.coursera.org/learn/os-power-user',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 28648,
                'price' => 0,
                'old_price' => null,
                'language_id' => 3,
                'category_id' => 1,
                'topic_id' => 4,
                'platform_id' => 1,
            ],
            [
                'title' => 'Ultimate Design Patterns',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5825958_ec29_3.jpg',
                'link' => 'https://www.udemy.com/course/ultimate-design-patterns/',
                'level' => 'beginner',
                'rating' => 4.9,
                'total_reviews' => 190,
                'price' => 64.99,
                'old_price' => null,
                'language_id' => 2,
                'category_id' => 1,
                'topic_id' => 4,
                'platform_id' => 5,
            ],
            [
                'title' => 'Computer Security and Systems Management Specialization',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/d8/e9f8707ade11e7b9f1b14397fa7f91/logo.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/specializations/computer-security-systems-management',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 1124,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 1,
                'topic_id' => 4,
                'platform_id' => 1,
            ],

            [
                'title' => 'Data Analysis and Visualization with Microsoft Power BI',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F670987b1_nd331%2Fnd331.jpg&w=1920&q=75',
                'link' => 'https://www.udacity.com/course/data-analysis-and-visualization-with-power-BI-nanodegree--nd331',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 94,
                'price' => 3560,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 2,
                'topic_id' => 5,
                'platform_id' => 4,
            ],
            [
                'title' => 'Python Komplet: Dari Nol Sampai Bisa!',
                'image' => 'https://img-c.udemycdn.com/course/240x135/2842590_a91c.jpg',
                'link' => 'https://www.udemy.com/course/python-komplet/',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 503,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 12,
                'category_id' => 2,
                'topic_id' => 5,
                'platform_id' => 5,
            ],
            [
                'title' => 'Data Science dalam Satu Minggu',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5191294_2df3_4.jpg',
                'link' => 'https://www.udemy.com/course/data-science-dalam-satu-minggu/',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 70,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 12,
                'category_id' => 2,
                'topic_id' => 5,
                'platform_id' => 5,
            ],
            [
                'title' => 'تحليل البيانات باستخدام باور بي اي -- Data Analysis Power BI',
                'image' => 'https://img-c.udemycdn.com/course/240x135/6034830_c669_3.jpg',
                'link' => 'https://www.udemy.com/course/data-analysis-using-knime/',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 342,
                'price' => 19.99,
                'old_price' => null,
                'language_id' => 2,
                'category_id' => 2,
                'topic_id' => 5,
                'platform_id' => 5,
            ],
            [
                'title' => 'Introduction to Data Analysis using Microsoft Excel',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/bc/dd4f095a8c426fa8fe044d1a756344/Diseno-sin-titulo-6-.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/projects/introduction-data-analysis-microsoft-excel',
                'level' => 'intermediate',
                'rating' => 4.7,
                'total_reviews' => 10,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 2,
                'topic_id' => 5,
                'platform_id' => 1,
            ],

            [
                'title' => 'Data Architect',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F6709875a_nd038%2Fnd038.jpg&w=1920&q=75',
                'link' => 'https://www.udacity.com/course/data-architect-nanodegree--nd038',
                'level' => 'expert',
                'rating' => 4.7,
                'total_reviews' => 91,
                'price' => 477,
                'old_price' => 794,
                'language_id' => 1,
                'category_id' => 2,
                'topic_id' => 6,
                'platform_id' => 4,
            ],
            [
                'title' => '(40+ Saat) Python | Sıfırdan İleri Seviye Programlama (2020)',
                'image' => 'https://img-c.udemycdn.com/course/240x135/1235124_7c5f_6.jpg',
                'link' => 'https://www.udemy.com/course/sifirdan-ileri-seviyeye-python/',
                'level' => 'expert',
                'rating' => 4.4,
                'total_reviews' => 45553,
                'price' => 10.99,
                'old_price' => 44.99,
                'language_id' => 5,
                'category_id' => 2,
                'topic_id' => 6,
                'platform_id' => 5,
            ],
            [
                'title' => 'Hadoop Big Data desde cero',
                'image' => 'https://img-c.udemycdn.com/course/240x135/713160_cca2_3.jpg',
                'link' => 'https://www.udemy.com/course/monta-un-cluster-hadoop-big-data-desde-cero/',
                'level' => 'expert',
                'rating' => 4.7,
                'total_reviews' => 2030,
                'price' => 10.99,
                'old_price' => 44.99,
                'language_id' => 3,
                'category_id' => 2,
                'topic_id' => 6,
                'platform_id' => 5,
            ],
            [
                'title' => '(CDAP) أخصائي تحليل البيانات المعتمد',
                'image' => 'https://img-c.udemycdn.com/course/240x135/6231601_928b_3.jpg',
                'link' => 'https://www.udemy.com/course/cdap-kml-ar/',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 50,
                'price' => 10.99,
                'old_price' => 34.99,
                'language_id' => 2,
                'category_id' => 2,
                'topic_id' => 6,
                'platform_id' => 5,
            ],

            [
                'title' => 'GenAI for Executives & Business Leaders: An Introduction',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/3a/b6cb2407ee4133913e4e7e1d53f752/2023_09_11_slowell_ai_academy_ks_kv_0166.fac5026.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/generative-ai-for-executives-business-leaders-introduction',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 338,
                'price' => 49,
                'old_price' => 60,
                'language_id' => 1,
                'category_id' => 2,
                'topic_id' => 7,
                'platform_id' => 1,
            ],
            [
                'title' => 'Introduction to Artificial Intelligence (AI)',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/a7/edd3b41ddd45298d7bbcb04b19fba6/200766_Logo-Image_1200x1200pxl-copy-3.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/introduction-to-ai',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 338,
                'price' => 49,
                'old_price' => 60,
                'language_id' => 4,
                'category_id' => 2,
                'topic_id' => 7,
                'platform_id' => 1,
            ],
            [
                'title' => 'Intelligence Artificielle de A à Z',
                'image' => 'https://img-c.udemycdn.com/course/240x135/1765870_b543.jpg',
                'link' => 'https://www.udemy.com/course/intelligence-artificielle-az/',
                'level' => 'beginner',
                'rating' => 4.5,
                'total_reviews' => 1975,
                'price' => 11.99,
                'old_price' => 49.99,
                'language_id' => 7,
                'category_id' => 2,
                'topic_id' => 7,
                'platform_id' => 5,
            ],
            [
                'title' => 'L’intelligence Artificielle générative pour débutants',
                'image' => 'https://img-c.udemycdn.com/course/240x135/6292379_f6af_10.jpg',
                'link' => 'https://www.udemy.com/course/lintelligence-artificielle-generative-pour-debutants/',
                'level' => 'beginner',
                'rating' => 4.5,
                'total_reviews' => 12,
                'price' => 10.99,
                'old_price' => 39.99,
                'language_id' => 7,
                'category_id' => 2,
                'topic_id' => 7,
                'platform_id' => 5,
            ],

            [
                'title' => 'Pandas Tutorial in Urdu/Hindi (Data Analysis in Python)',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3201760_48f7_4.jpg',
                'link' => 'https://www.udemy.com/course/pandas-tutorial-in-urduhindi-data-analysis-in-python/',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 17,
                'category_id' => 2,
                'topic_id' => 8,
                'platform_id' => 5,
            ],
            [
                'title' => 'Sales data analysis in python, Urdu/Hindi',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5797946_4795.jpg',
                'link' => 'https://www.udemy.com/course/sales-data-analysis-in-python-urduhindi/',
                'level' => 'intermediate',
                'rating' => 4.9,
                'total_reviews' => 5,
                'price' => 0,
                'old_price' => null,
                'language_id' => 17,
                'category_id' => 2,
                'topic_id' => 8,
                'platform_id' => 5,
            ],
            [
                'title' => 'Machine Learning Specialization',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/3a/9d2a7af297483a845340bcfbac6f1e/MLS.course-banners-01_Course-Logo-.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/specializations/machine-learning-introduction',
                'level' => 'beginner',
                'rating' => 4.9,
                'total_reviews' => 31401,
                'price' => 49,
                'old_price' => 80,
                'language_id' => 1,
                'category_id' => 2,
                'topic_id' => 8,
                'platform_id' => 1,
            ],
            [
                'title' => 'Data for Machine Learning',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0a/2934226fd34d5694390958251cd774/ML-Improving-Machine-Learning_1.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/learn/data-machine-learning',
                'level' => 'intermediate',
                'rating' => 4.4,
                'total_reviews' => 98,
                'price' => 50,
                'old_price' => 80,
                'language_id' => 1,
                'category_id' => 2,
                'topic_id' => 8,
                'platform_id' => 1,
            ],

            [
                'title' => 'Business Intelligence Analytics',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F670987b4_nd429%2Fnd429.jpg&w=1080&q=75',
                'link' => 'https://www.udacity.com/course/business-intelligence-analytics-nanodegree--nd429',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 3560,
                'old_price' => 4000,
                'language_id' => 1,
                'category_id' => 2,
                'topic_id' => 9,
                'platform_id' => 4,
            ],
            [
                'title' => 'Ciencia de Datos y Analítica de Negocio con Python y ChatGPT',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5320790_b5bc_3.jpg',
                'link' => 'https://www.udemy.com/course/business-analytics-con-python-y-chatgpt-de-cero-a-experto/',
                'level' => 'expert',
                'rating' => 4.6,
                'total_reviews' => 132,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 3,
                'category_id' => 2,
                'topic_id' => 9,
                'platform_id' => 5,
            ],
            [
                'title' => 'Aprende Business Intelligence con Qliksense desde cero',
                'image' => 'https://img-c.udemycdn.com/course/240x135/2809495_0dc4.jpg',
                'link' => 'https://www.udemy.com/course/business-analytics-con-python-y-chatgpt-de-cero-a-experto/',
                'level' => 'beginner',
                'rating' => 4.0,
                'total_reviews' => 11,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 3,
                'category_id' => 2,
                'topic_id' => 9,
                'platform_id' => 5,
            ],

            [
                'title' => 'Intermediate JavaScript',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F67098750_nd032%2Fnd032.jpg&w=1920&q=75',
                'link' => 'https://www.udacity.com/course/intermediate-javascript-nanodegree--nd032',
                'level' => 'intermediate',
                'rating' => 4.4,
                'total_reviews' => 140,
                'price' => 2136,
                'old_price' => 3560,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 11,
                'platform_id' => 4,
            ],
            [
                'title' => 'Angular - The Complete Guide (2025 Edition)',
                'image' => 'https://img-c.udemycdn.com/course/240x135/756150_c033_4.jpg',
                'link' => 'https://www.udemy.com/course/the-complete-guide-to-angular-2/',
                'level' => 'intermediate',
                'rating' => 4.7,
                'total_reviews' => 212600,
                'price' => 15.99,
                'old_price' => 94.99,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 11,
                'platform_id' => 5,
            ],
            [
                'title' => 'The PHP 8 Learning Guide',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3950826_0ce7_2.jpg',
                'link' => 'https://www.udemy.com/course/php-8-guide-2021-edition/',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 848,
                'price' => 11.99,
                'old_price' => 44.99,
                'language_id' => 2,
                'category_id' => 3,
                'topic_id' => 11,
                'platform_id' => 5,
            ],
            [
                'title' => 'Desarrollo Web con Spring 4',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3950826_0ce7_2.jpg',
                'link' => 'https://www.udemy.com/course/desarrollo-web-con-spring/',
                'level' => 'expert',
                'rating' => 4.1,
                'total_reviews' => 642,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 3,
                'category_id' => 3,
                'topic_id' => 11,
                'platform_id' => 5,
            ],

            [
                'title' => 'Android App Development Specialization',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/ca/bd3c40bb0811e5ba54dbc0616c905c/AAD-settings.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/specializations/android-app-development',
                'level' => 'beginner',
                'rating' => 4.5,
                'total_reviews' => 2853,
                'price' => 49,
                'old_price' => 97.7,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 12,
                'platform_id' => 1,
            ],
            [
                'title' => 'Meta iOS Developer Professional Certificate',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/4b/90dd15592e4db788410bc928b93e52/iOS-dev-ProCert.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/professional-certificates/meta-ios-developer',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 1656,
                'price' => 49,
                'old_price' => 97.7,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 12,
                'platform_id' => 1,
            ],
            [
                'title' => 'Advanced App Development in Android Specialization',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/8c/724b84a947419482168e176f34a4cf/AADA_Icon-01.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/specializations/advanced-app-android',
                'level' => 'intermediate',
                'rating' => 4.1,
                'total_reviews' => 74,
                'price' => 49,
                'old_price' => 97.7,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 12,
                'platform_id' => 1,
            ],

            [
                'title' => 'Software Testing kursuna ilk adim',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5225086_39df_3.jpg',
                'link' => 'https://www.udemy.com/course/sdet-i-10-derste-ogrenin/',
                'level' => 'beginner',
                'rating' => 4.5,
                'total_reviews' => 2,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 5,
                'category_id' => 3,
                'topic_id' => 14,
                'platform_id' => 5,
            ],

            [
                'title' => 'Programming Languages, Part A',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/9b/39a3f0373111e69ce719fe5f0d2d9d/Capture.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/programming-languages',
                'level' => 'intermediate',
                'rating' => 4.9,
                'total_reviews' => 1886,
                'price' => 45,
                'old_price' => 90.7,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 15,
                'platform_id' => 1,
            ],
            [
                'title' => '100 Days of Code: The Complete Python Pro Bootcamp',
                'image' => 'https://img-c.udemycdn.com/course/240x135/2776760_f176_10.jpg',
                'link' => 'https://www.udemy.com/course/100-days-of-code/',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 355869,
                'price' => 17.99,
                'old_price' => 109.9,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 15,
                'platform_id' => 5,
            ],

            [
                'title' => 'Advanced Database Design Patterns in Action',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5765004_f66c_87.jpg',
                'link' => 'https://www.udemy.com/course/advanced-database-design-patterns-in-action/',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 20,
                'price' => 10.99,
                'old_price' => 39.9,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 16,
                'platform_id' => 5,
            ],
            [
                'title' => 'Advanced Database Design Patterns in Action',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/83/c9a3279c4247529775d5f41cb1d3a0/DBA-ProCert.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/professional-certificates/meta-database-engineer',
                'level' => 'intermediate',
                'rating' => 4.6,
                'total_reviews' => 2119,
                'price' => 18.99,
                'old_price' => 39.9,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 16,
                'platform_id' => 1,
            ],
            [
                'title' => 'Introduction to Database Migration',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/a4/134c9887a14b2aac08fcf7bd921657/Screenshot-2024-03-19-at-4.40.41-PM.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/learn/aws-introduction-to-database-migration-paxaf',
                'level' => 'beginner',
                'rating' => 4.9,
                'total_reviews' => 7,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 16,
                'platform_id' => 1,
            ],
            [
                'title' => 'SQL',
                'image' => 'https://www.udacity.com/_next/image?url=https%3A%2F%2Fvideo.udacity-data.com%2Ftopher%2F2024%2FOctober%2F6709876a_nd072%2Fnd072.jpg&w=1080&q=75',
                'link' => 'https://www.udacity.com/course/learn-sql--nd072',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 288,
                'price' => 2136,
                'old_price' => 3560,
                'language_id' => 1,
                'category_id' => 3,
                'topic_id' => 16,
                'platform_id' => 4,
            ],

            [
                'title' => 'Film, Images & Historical Interpretation in the 20th Century: The Camera Never Lies',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/46/fb5637e5b6d4e71b0b97cfeb0aec55/Flag-raising-on-Iwo-Jima.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=204&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/film-images',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 377,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 4,
                'topic_id' => 17,
                'platform_id' => 1,
            ],

            [
                'title' => 'Introduction to Philosophy',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/04/d57b80c12111e694fd8bca8aebde40/school-of-athens-raphael-1080x1080.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/philosophy',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 9498,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 4,
                'topic_id' => 18,
                'platform_id' => 1,
            ],

            [
                'title' => 'تحسين الصوت وتطوير مهارته-الجزء الأول-خصائص الصوت ومهاراته',
                'image' => 'https://img-c.udemycdn.com/course/240x135/6316949_3d8f.jpg',
                'link' => 'https://www.udemy.com/course/improving_vocal_skills/',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 288,
                'price' => 10.99,
                'old_price' => 39.9,
                'language_id' => 2,
                'category_id' => 4,
                'topic_id' => 19,
                'platform_id' => 5,
            ],
            [
                'title' => 'Curso Completo de Violão + 3 Revistas Digitais Grátis',
                'image' => 'https://img-c.udemycdn.com/course/240x135/1420920_69e8.jpg',
                'link' => 'https://www.udemy.com/course/curso-completo-de-violao/?couponCode=ST10MT30325G1',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 1086,
                'price' => 10.99,
                'old_price' => 39.9,
                'language_id' => 4,
                'category_id' => 4,
                'topic_id' => 19,
                'platform_id' => 5,
            ],

            [
                'title' => 'English for Journalism',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/e0/49bdb0120e11e6a2d7a90dc288791b/Journalism.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/journalism',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 2801,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 4,
                'topic_id' => 20,
                'platform_id' => 1,
            ],
            [
                'title' => '로봇으로 기사를 작성해보자:로봇 저널리즘 입문(Introduction to Robot Journalism)',
                'image' => 'https://img-c.udemycdn.com/course/240x135/852858_463b_2.jpg',
                'link' => 'https://www.udemy.com/course/introduction-to-algorithm-reporting/',
                'level' => 'intermediate',
                'rating' => 2.4,
                'total_reviews' => 12,
                'price' => 0,
                'old_price' => null,
                'language_id' => 8,
                'category_id' => 4,
                'topic_id' => 20,
                'platform_id' => 5,
            ],

            [
                'title' => 'Leadership Principles',
                'image' => 'https://cloudinary.hbs.edu/hbsit/image/upload/s--8uDGXGee--/f_auto,c_fill,h_213,w_380,/v20200101/76F19FCCA43714EC036695F6C82B2A1E.jpg',
                'link' => 'https://online.hbs.edu/courses/leadership-principles/',
                'level' => 'intermediate',
                'rating' => null,
                'total_reviews' => null,
                'price' => 1850,
                'old_price' => 2000,
                'language_id' => 1,
                'category_id' => 5,
                'topic_id' => 21,
                'platform_id' => 2,
            ],
            [
                'title' => 'Credential of Leadership, Impact, and Management in Business (CLIMB)',
                'image' => 'https://cloudinary.hbs.edu/hbsit/image/upload/s--StsVwFQr--/f_auto,c_fill,h_213,w_380,/v20200101/E35D4664D1081E2EFC38E8A2006ECC49.jpg',
                'link' => 'https://online.hbs.edu/courses/climb/',
                'level' => 'intermediate',
                'rating' => null,
                'total_reviews' => null,
                'price' => 15000,
                'old_price' => 2000,
                'language_id' => 1,
                'category_id' => 5,
                'topic_id' => 21,
                'platform_id' => 2,
            ],
            [
                'title' => 'Organizational Leadership',
                'image' => 'https://cloudinary.hbs.edu/hbsit/image/upload/s--edj-tQcX--/f_auto,c_fill,h_213,w_380,/v20200101/EFAADCDEA1C0BF879F39C5DB12631DB7.jpg',
                'link' => 'https://online.hbs.edu/courses/organizational-leadership/',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 1850,
                'old_price' => 2100,
                'language_id' => 1,
                'category_id' => 5,
                'topic_id' => 21,
                'platform_id' => 2,
            ],

            [
                'title' => 'Primavera P6 Professional Training In Urdu/Hindi',
                'image' => 'https://img-c.udemycdn.com/course/240x135/2141260_7bfc_3.jpg',
                'link' => 'https://www.udemy.com/course/primavera-p6-professional-beginner-to-expert-urduhindi/',
                'level' => 'beginner',
                'rating' => 4.4,
                'total_reviews' => 28,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 17,
                'category_id' => 5,
                'topic_id' => 23,
                'platform_id' => 5,
            ],
            [
                'title' => 'Google Project Management: Professional Certificate',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/bf/b07da9bbe24cb8b0daa00010ff8b22/1060x596_GCC-photos_Ashley.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=320&h=180&fit=crop&q=50&crop=faces',
                'link' => 'https://www.coursera.org/professional-certificates/google-project-management',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 114518,
                'price' => 50,
                'old_price' => 80.99,
                'language_id' => 1,
                'category_id' => 5,
                'topic_id' => 23,
                'platform_id' => 1,
            ],

            [
                'title' => 'Financial Accounting',
                'image' => 'https://cloudinary.hbs.edu/hbsit/image/upload/s--ISJiX3Xd--/f_auto,c_fill,h_213,w_380,/v20200101/7A17F1400DE19FAF007B59A36791C521.jpg',
                'link' => 'https://online.hbs.edu/courses/financial-accounting/',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 1850,
                'old_price' => 2000,
                'language_id' => 1,
                'category_id' => 5,
                'topic_id' => 25,
                'platform_id' => 2,
            ],

            [
                'title' => 'Introducción al Cálculo Vectorial (en varias variables)',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5073840_6710_3.jpg',
                'link' => 'https://www.udemy.com/course/introduccion-al-calculo-vectorial/?couponCode=LETSLEARNNOW',
                'level' => 'intermediate',
                'rating' => 5,
                'total_reviews' => 2,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 3,
                'category_id' => 6,
                'topic_id' => 26,
                'platform_id' => 5,
            ],
            [
                'title' => 'Magnétisme et Pendule',
                'image' => 'https://img-c.udemycdn.com/course/240x135/6388549_6f41_2.jpg',
                'link' => 'https://www.udemy.com/course/magnetisme-et-pendule/?couponCode=LETSLEARNNOW',
                'level' => 'intermediate',
                'rating' => null,
                'total_reviews' => null,
                'price' => 34.0,
                'old_price' => 60.99,
                'language_id' => 7,
                'category_id' => 6,
                'topic_id' => 26,
                'platform_id' => 5,
            ],
            [
                'title' => 'Understanding Modern Physics I: Relativity and Cosmology',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/22/5776ec72504b3ab4bfb34c10bc40fc/part-1_1.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/understanding-modern-physics-1-relativity-and-cosmology',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 146,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 6,
                'topic_id' => 26,
                'platform_id' => 1,
            ],

            [
                'title' => 'Introduction to Physical Chemistry',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/63/6034e2bcadd6c166a0697a0d63141a/graphene.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/physical-chemistry',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 713,
                'price' => 60,
                'old_price' => 88,
                'language_id' => 1,
                'category_id' => 6,
                'topic_id' => 27,
                'platform_id' => 1,
            ],
            [
                'title' => 'Chemistry + Python: Solve chemistry problems with Python',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3175884_826a_5.jpg',
                'link' => 'https://www.udemy.com/course/introduction-to-python-for-chemistry/',
                'level' => 'beginner',
                'rating' => 4.7,
                'total_reviews' => 713,
                'price' => 59.99,
                'old_price' => 113.0,
                'language_id' => 1,
                'category_id' => 6,
                'topic_id' => 27,
                'platform_id' => 5,
            ],

            [
                'title' => 'Mindfulness',
                'image' => 'https://img-c.udemycdn.com/course/240x135/4550088_f9ef.jpg',
                'link' => 'https://www.udemy.com/course/mindfulness-simdi-ve-burada/',
                'level' => 'intermediate',
                'rating' => 4.7,
                'total_reviews' => 713,
                'price' => 59.99,
                'old_price' => 113.0,
                'language_id' => 5,
                'category_id' => 7,
                'topic_id' => 30,
                'platform_id' => 5,
            ],
            [
                'title' => 'Vital Signs: Understanding What the Body Is Telling Us',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/55/8d2e309e6811e3bf47177a6a987fca/Vital-Signs-1.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/vital-signs',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 6637,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 7,
                'topic_id' => 30,
                'platform_id' => 1,
            ],

            [
                'title' => 'Ultimate Obesity Certification : Learn Practical Management',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5537024_c2aa_3.jpg',
                'link' => 'https://www.udemy.com/course/ultimate-obesity-certification-learn-practical-management/?couponCode=LETSLEARNNOW',
                'level' => 'expert',
                'rating' => 4.6,
                'total_reviews' => 52,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 17,
                'category_id' => 7,
                'topic_id' => 32,
                'platform_id' => 5,
            ],

            [
                'title' => 'Sports Nutrition Diploma',
                'image' => 'https://img-c.udemycdn.com/course/240x135/6178225_3c75_4.jpg',
                'link' => 'https://www.udemy.com/course/sports-nutrition-diploma/?couponCode=LETSLEARNNOW',
                'level' => 'intermediate',
                'rating' => 5,
                'total_reviews' => 6,
                'price' => 29.99,
                'old_price' => 48.99,
                'language_id' => 2,
                'category_id' => 7,
                'topic_id' => 33,
                'platform_id' => 5,
            ],
            [
                'title' => 'Nutrition for Inflammation - The Anti-inflammatory Diet',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3147206_a7b7_2.jpg',
                'link' => 'https://www.udemy.com/course/nutrition-for-inflammation/',
                'level' => 'beginner',
                'rating' => 4.6,
                'total_reviews' => 52,
                'price' => 59.99,
                'old_price' => 70.99,
                'language_id' => 1,
                'category_id' => 7,
                'topic_id' => 33,
                'platform_id' => 5,
            ],
            [
                'title' => 'Personal trainer de sucesso',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3606174_0faf.jpg',
                'link' => 'https://www.udemy.com/course/personal-trainer-de-sucesso/',
                'level' => 'beginner',
                'rating' => 4.5,
                'total_reviews' => 55,
                'price' => 19.99,
                'old_price' => 44.99,
                'language_id' => 4,
                'category_id' => 7,
                'topic_id' => 33,
                'platform_id' => 5,
            ],

            [
                'title' => 'Digital Marketing Strategy',
                'image' => 'https://cloudinary.hbs.edu/hbsit/image/upload/s--S-a8q2iP--/f_auto,c_fill,h_382,w_680,/v20200101/54DA7A9FABC4C3AC5B7110AD1525FB2F.jpg',
                'link' => 'https://online.hbs.edu/courses/digital-marketing-strategy/',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 1850,
                'old_price' => 2200,
                'language_id' => 1,
                'category_id' => 8,
                'topic_id' => 35,
                'platform_id' => 2,
            ],
            [
                'title' => 'Credential of Digital Innovation and Strategy',
                'image' => 'https://cloudinary.hbs.edu/hbsit/image/upload/s--VlMrFlz8--/f_auto,c_fill,h_213,w_380,/v20200101/07B4ADEA8D03F082672AFC1FE01E32AA.jpg',
                'link' => 'https://online.hbs.edu/courses/digital-innovation-strategy-credential/',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 6500,
                'old_price' => 7000,
                'language_id' => 1,
                'category_id' => 8,
                'topic_id' => 35,
                'platform_id' => 2,
            ],
            [
                'title' => 'Winning with Digital Platforms',
                'image' => 'https://cloudinary.hbs.edu/hbsit/image/upload/s--gOrsbf6N--/f_auto,c_fill,h_213,w_380,/v20200101/F007F44C15A01A1E56DA5CEF6C38DDC3.jpg',
                'link' => 'https://online.hbs.edu/courses/winning-with-digital-platforms/',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 1850,
                'old_price' => 2100,
                'language_id' => 1,
                'category_id' => 8,
                'topic_id' => 35,
                'platform_id' => 2,
            ],

            [
                'title' => 'The Science of Well-Being',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/7e/aff5b0f54c11e7b5ae579a0e963c38/Logo_TheScienceofWell-Being.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/the-science-of-well-being',
                'level' => 'beginner',
                'rating' => null,
                'total_reviews' => null,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 37,
                'platform_id' => 1,
            ],
            [
                'title' => 'English for Interactions in the Workplace Intermediate Level',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/49/2df92782d84e72b7117a2d78883254/img-coursera.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/learn/english-for-interactions-in-the-workplace-intermediate-level',
                'level' => 'intermediate',
                'rating' => 4.7,
                'total_reviews' => 227,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 37,
                'platform_id' => 1,
            ],
            [
                'title' => 'Learn English: Advanced Grammar and Punctuation Specialization',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/ee/57fb00659311e6bf3629182543e660/grammar-2.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/specializations/advanced-grammar-punctuation',
                'level' => 'expert',
                'rating' => 4.8,
                'total_reviews' => 2023,
                'price' => 1500,
                'old_price' => 1800,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 37,
                'platform_id' => 1,
            ],

            [
                'title' => 'Chinese for Beginners',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/3f/e014c0ba7811e5a05e970d8586e01d/___-1.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/learn-chinese',
                'level' => 'expert',
                'rating' => 4.8,
                'total_reviews' => 19764,
                'price' => 1850,
                'old_price' => 2000,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 38,
                'platform_id' => 1,
            ],
            [
                'title' => 'Learn Chinese Language: Everyday & Business Chinese BEGINNER',
                'image' => 'https://img-c.udemycdn.com/course/240x135/4905216_3f06_3.jpg',
                'link' => 'https://www.udemy.com/course/learn-chinese-language-everyday-business-chinese/',
                'level' => 'expert',
                'rating' => 4.9,
                'total_reviews' => 142,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 38,
                'platform_id' => 5,
            ],

            [
                'title' => 'The Complete Korean Course for Beginners | 10 courses in 1',
                'image' => 'https://img-c.udemycdn.com/course/240x135/2520960_a91b_6.jpg',
                'link' => 'https://www.udemy.com/course/korean-for-absolute-beginners-1/',
                'level' => 'beginner',
                'rating' => 4.1,
                'total_reviews' => 4331,
                'price' => 59.99,
                'old_price' => 89.99,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 39,
                'platform_id' => 5,
            ],
            [
                'title' => 'Korean Pronunciation Masterclass',
                'image' => 'https://img-c.udemycdn.com/course/240x135/3269112_e47d_2.jpg',
                'link' => 'https://www.udemy.com/course/korean-pronunciation-masterclass/?couponCode=LETSLEARNNOW',
                'level' => 'beginner',
                'rating' => 4.8,
                'total_reviews' => 55,
                'price' => 22.99,
                'old_price' => 44.99,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 39,
                'platform_id' => 5,
            ],
            [
                'title' => 'First Step Korean',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/7b/3030708c3111e5ae965dd3ea8cdc5d/________03.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/learn-korean',
                'level' => 'beginner',
                'rating' => 4.9,
                'total_reviews' => 51993,
                'price' => 59.99,
                'old_price' => 89.99,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 39,
                'platform_id' => 1,
            ],

            [
                'title' => 'Arabic Language COMPLETE course The Secret of Levantine',
                'image' => 'https://img-c.udemycdn.com/course/240x135/5351754_3cce_3.jpg',
                'link' => 'https://www.udemy.com/course/the-secret-of-levantine-arabic/',
                'level' => 'beginner',
                'rating' => 5,
                'total_reviews' => 45,
                'price' => 19.99,
                'old_price' => 29.99,
                'language_id' => 1,
                'category_id' => 9,
                'topic_id' => 40,
                'platform_id' => 5,
            ],

            [
                'title' => 'Interactive Computer Graphics',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/bd/fb88d0e9bc11e5abe1133ac5dcedb7/InteractiveComputerGraphics.png?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/interactive-computer-graphics',
                'level' => 'intermediate',
                'rating' => 4.1,
                'total_reviews' => 304,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 10,
                'topic_id' => 41,
                'platform_id' => 1,
            ],
            [
                'title' => 'Machine Design Part I',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/0f/b90b206eb511e6a1c0d77b7ec6029c/machine_design_coursera_icon.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&fit=crop&q=50',
                'link' => 'https://www.coursera.org/learn/machine-design1',
                'level' => 'intermediate',
                'rating' => 4.8,
                'total_reviews' => 2176,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 10,
                'topic_id' => 41,
                'platform_id' => 1,
            ],

            [
                'title' => 'Kullanıcı araştırması nedir ve nasıl yapılır',
                'image' => 'https://img-c.udemycdn.com/course/240x135/4392856_d92f.jpg',
                'link' => 'https://www.udemy.com/course/ux-kullanici-arastirmasi-nedir-ve-nasil-yapilir-sherpa-egitim-kurs/?couponCode=LETSLEARNNOW',
                'level' => 'intermediate',
                'rating' => 4.2,
                'total_reviews' => 25,
                'price' => 10.99,
                'old_price' => 19.99,
                'language_id' => 5,
                'category_id' => 10,
                'topic_id' => 43,
                'platform_id' => 5,
            ],
            [
                'title' => 'Introduction to User Experience Design',
                'image' => 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/6c/0d3ca034c411e694968959655359ff/IntroductionUser_InterfaceDesignPart1.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=216&q=50&fit=crop',
                'link' => 'https://www.coursera.org/learn/user-experience-design',
                'level' => 'beginner',
                'rating' => 4.5,
                'total_reviews' => 8579,
                'price' => 0,
                'old_price' => null,
                'language_id' => 1,
                'category_id' => 10,
                'topic_id' => 43,
                'platform_id' => 1,
            ],
        ];

        Course::insert($courses);
    }
}
